# Adapted from https://github.com/sbt/sbt-native-packager/blob/master/appveyor.yml
version: '{build}'
os: Windows Server 2012

environment:
  matrix:
  - JAVA_OPTS: -Dfile.encoding=UTF8
    JAVA_HOME: C:\Program Files\Java\jdk9
    TEST_TASKS: ops[2.11.12].test terminal[2.12.6].test amm.repl[2.12.6].test terminal[2.13.0-M5].test amm.repl[2.13.0-M5].test

  - JAVA_OPTS: -Dfile.encoding=UTF8
    JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    TEST_TASKS: amm[2.11.12].test integration[2.12.6].test integration[2.13.0-M5].test

install:
  - SET MILL_URL=https://github.com/lihaoyi/mill/releases/download/0.2.7/0.2.7

build_script:
  - SET "PATH=%JAVA_HOME%\bin;%PATH%"
  - MD C:\bin
  - curl -Lo C:\bin\mill.bat %MILL_URL%

test_script:
  - cmd /C C:\bin\mill.bat -i all %TEST_TASKS%

cache:
  - '%LOCALAPPDATA%\Coursier\cache'
