# Adapted from https://github.com/sbt/sbt-native-packager/blob/master/appveyor.yml
version: '{build}'
os: Windows Server 2012

environment:
  matrix:
  - JAVA_OPTS: -Dfile.encoding=UTF8
    JAVA_HOME: C:\Program Files\Java\jdk9
    TEST_TASKS: terminal[2.12.12].test amm.repl[2.12.12].test terminal[2.13.3].test amm.repl[2.13.3].test

  - JAVA_OPTS: -Dfile.encoding=UTF8
    JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    TEST_TASKS: integration[2.12.12].test integration[2.13.3].test

install:
  - SET MILL_URL=https://github.com/lihaoyi/mill/releases/download/0.7.0/0.7.0-assembly

build_script:
  - SET "PATH=%JAVA_HOME%\bin;%PATH%"
  - MD C:\bin
  - curl -Lo C:\bin\mill.bat %MILL_URL%

test_script:
  - cmd /C C:\bin\mill.bat -i all %TEST_TASKS%

cache:
  - '%LOCALAPPDATA%\Coursier\cache'
